notifications:
  email: false
dist: trusty
sudo: false
group: beta
language: node_js
cache:
  directories:
  - "$HOME/.npm"
install: case $TRAVIS_BRANCH in greenkeeper*) npm i;; *) npm ci;; esac;
jobs:
  include:
  - stage: test
    script:
    - set -e
    - npm run prepare-templates
    - npm run lint
    - npm run test
    - npm run coverage
