notifications:
  email: false
dist: trusty
sudo: false
group: beta
language: node_js
cache:
  directories:
  - "$HOME/.npm"
install: case $TRAVIS_BRANCH in greenkeeper*) npm i;; *) npm ci;; esac;
jobs:
  include:
  - stage: test
    script:
    - set -e
    - npm run pull-submodules
    - npm run prepare-templates
    - npm run lint
    - npm run test
    - npm run coverage
  - stage: NPM release
    if: tag IS present
    script: echo 'Deploying to NPM...'
    before_deploy:
    - npm run prepare-templates
    - npm run build
    deploy:
      provider: npm
      email: chadima.jiri@gmail.com
      skip_cleanup: true
      api_key: "$NPM_TOKEN"
      on:
        repo: fragaria/address-formatter
        tags: true
env:
  global:
    secure: VL6kalMLtaDYcaDlhCZ/X876JY5oZa+dXZ0rz88E7KKlKgSRJia28DmVo6yeAaTkpF9xuHcHci1GOlbva5xRcesMZ+dx041HaJH0gQTn27/DwAz46JkY17JSsXz1hG//TuXBfwQzOKOCMAMKxS8tYFWqnekLZbJOb3+d//cRTuK1MHkeb/VpIVBJzr5fb9hfTIGZxdCMd+kCG24Pk3pk+pHr5974taOqxTTmAhpRY73f50DDTp8Sg+gGQr9cYCWPkP5hi7H5LBUjLyPN8zY1874hFm5SA2sP83BDs96NG1tcfWju68Y1d5Xc51NhQLjN5jDM74aMHDJWAA/QK2R8R3Yrpt7p5JxCm3Qjh43+jvFMBCXUqrPKQYtZiZWNW+Gr+oaAwv1+zHl1r6x/nm1SyuY7fGG14h3Mt+ItO955dDQaBKjjJMHX+UpbfZDiFFBXvzR1+NQFKYfJT94bowz48aVSnhXsHT50J2bvkLJ6OtlqUb68BeBO3FmMlioMH9Gs7xO0BoCqUV0yRBde1QbPzW0wl1SaBG/eqf9ccAEdB9K5GSRgj8NYtWSH9MfrgW//M/M8gcukmb7sDsxLmaecbGqwFh0j//kCPPZoqznlwHj8SImsFzJXTz15dHeN0YGVGPRzf6IAxFpHQqtkaiuTqmgt+JE6KJq7jUghmZpYezo=
